-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 23:47:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema thinkeat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `thinkeat` ;

-- -----------------------------------------------------
-- Schema thinkeat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thinkeat` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `thinkeat` ;

-- -----------------------------------------------------
-- Table `thinkeat`.`access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`access` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`access` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `access_function` VARCHAR(255) NULL DEFAULT NULL,
  `access_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`authority` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`authority` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `authority_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`authority_access`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`authority_access` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`authority_access` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `access_id` INT NULL DEFAULT NULL,
  `authority_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKbue1hqhv9vm8c99h3vvh3fvww` (`access_id` ASC) VISIBLE,
  INDEX `FKs6wffn7jekrys2yw1pog7uiyt` (`authority_id` ASC) VISIBLE,
  CONSTRAINT `FKbue1hqhv9vm8c99h3vvh3fvww`
    FOREIGN KEY (`access_id`)
    REFERENCES `thinkeat`.`access` (`id`),
  CONSTRAINT `FKs6wffn7jekrys2yw1pog7uiyt`
    FOREIGN KEY (`authority_id`)
    REFERENCES `thinkeat`.`authority` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`user` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nick_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `authority_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKokrgxdbtf7tirfx1d1qtg9n24` (`authority_id` ASC) VISIBLE,
  CONSTRAINT `FKokrgxdbtf7tirfx1d1qtg9n24`
    FOREIGN KEY (`authority_id`)
    REFERENCES `thinkeat`.`authority` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`restaurant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`price` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`price` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`eatrepo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`eatrepo` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`eatrepo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `article` VARCHAR(255) NULL DEFAULT NULL,
  `date` TIMESTAMP NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `price_id` INT NULL DEFAULT NULL,
  `restaurant_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKamogkeopgokjk7oga8nqv25qi` (`user_id` ASC) VISIBLE,
  INDEX `FKq2cbcwanu8or8d3r8be3e9t7e` (`price_id` ASC) VISIBLE,
  INDEX `FKlvrngxpspqlrn889h89xa3xow` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `FKamogkeopgokjk7oga8nqv25qi`
    FOREIGN KEY (`user_id`)
    REFERENCES `thinkeat`.`user` (`id`),
  CONSTRAINT `FKlvrngxpspqlrn889h89xa3xow`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `thinkeat`.`restaurant` (`id`),
  CONSTRAINT `FKq2cbcwanu8or8d3r8be3e9t7e`
    FOREIGN KEY (`price_id`)
    REFERENCES `thinkeat`.`price` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`comment` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comment_context` VARCHAR(255) NULL DEFAULT NULL,
  `date` TIMESTAMP NULL DEFAULT NULL,
  `eatrepo_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK6fkj5llv13f9clbpxj0c0pll8` (`eatrepo_id` ASC) VISIBLE,
  INDEX `FK8kcum44fvpupyw6f5baccx25c` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK6fkj5llv13f9clbpxj0c0pll8`
    FOREIGN KEY (`eatrepo_id`)
    REFERENCES `thinkeat`.`eatrepo` (`id`),
  CONSTRAINT `FK8kcum44fvpupyw6f5baccx25c`
    FOREIGN KEY (`user_id`)
    REFERENCES `thinkeat`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`tag` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`eatrepo_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`eatrepo_tag` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`eatrepo_tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `eatrepo_id` INT NULL DEFAULT NULL,
  `tag_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKly2gb8gkn1si4fgmj0y1fyex3` (`eatrepo_id` ASC) VISIBLE,
  INDEX `FKeqig3fpcogmh2ix19ahf87h6k` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `FKeqig3fpcogmh2ix19ahf87h6k`
    FOREIGN KEY (`tag_id`)
    REFERENCES `thinkeat`.`tag` (`id`),
  CONSTRAINT `FKly2gb8gkn1si4fgmj0y1fyex3`
    FOREIGN KEY (`eatrepo_id`)
    REFERENCES `thinkeat`.`eatrepo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`favlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`favlist` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`favlist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `list_id` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK1yyp986gfslayyywmlq842k3h` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK1yyp986gfslayyywmlq842k3h`
    FOREIGN KEY (`user_id`)
    REFERENCES `thinkeat`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`favlist_eatrepo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`favlist_eatrepo` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`favlist_eatrepo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `eatrepo_id` INT NULL DEFAULT NULL,
  `favlist_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKdtq89a4gilmbqxjoi0c4s2keu` (`eatrepo_id` ASC) VISIBLE,
  INDEX `FK5dgc1uauxkxlg3g54iyimrup7` (`favlist_id` ASC) VISIBLE,
  CONSTRAINT `FK5dgc1uauxkxlg3g54iyimrup7`
    FOREIGN KEY (`favlist_id`)
    REFERENCES `thinkeat`.`favlist` (`id`),
  CONSTRAINT `FKdtq89a4gilmbqxjoi0c4s2keu`
    FOREIGN KEY (`eatrepo_id`)
    REFERENCES `thinkeat`.`eatrepo` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `thinkeat`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thinkeat`.`picture` ;

CREATE TABLE IF NOT EXISTS `thinkeat`.`picture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_path` VARCHAR(255) NULL DEFAULT NULL,
  `filename` VARCHAR(255) NULL DEFAULT NULL,
  `html_path` VARCHAR(255) NULL DEFAULT NULL,
  `eatrepo_id` INT NULL DEFAULT NULL,
  `restaurant_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKidxtu2736ehbnowps61ydkdru` (`eatrepo_id` ASC) VISIBLE,
  INDEX `FKinqrbkoct9u536o2nut30rc6i` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `FKidxtu2736ehbnowps61ydkdru`
    FOREIGN KEY (`eatrepo_id`)
    REFERENCES `thinkeat`.`eatrepo` (`id`),
  CONSTRAINT `FKinqrbkoct9u536o2nut30rc6i`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `thinkeat`.`restaurant` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
